# Generated by Django 3.2.24 on 2024-03-18 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Polycystic_ovarian_syndrome_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.CharField(max_length=50)),
                ('weight', models.CharField(max_length=50)),
                ('bmi', models.CharField(max_length=50)),
                ('hirsutism', models.CharField(max_length=50)),
                ('skin', models.CharField(default=None, max_length=25)),
                ('acene', models.CharField(default=None, max_length=10)),
                ('menstrual', models.CharField(default=None, max_length=10)),
                ('sleep', models.CharField(default=None, max_length=10)),
                ('hair', models.CharField(default=None, max_length=10)),
                ('result1', models.CharField(default=None, max_length=100)),
                ('result2', models.CharField(default='null', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Polycystic_ovarian_syndrome_App.user')),
            ],
            options={
                'db_table': 'history',
            },
        ),
    ]
